version: '3.1'

services:
  db:
    image: postgres:10.3-alpine
    container_name: warehouse_db
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      PGDATA: /data/postgres
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT:-5432}:5432
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: warehouse
